#!/bin/bash
# Basic while loop
############################ acc based search #############################
#quant=16
#while [ $quant -ge 8 ]
#do
#	python findoptimal.py --acc 72.3 --pr 0 --quant $quant --channelscaling 1
#	python findoptimal.py --acc 72.3 --pr 50 --quant $quant --channelscaling 1
#	python findoptimal.py --acc 72.3 --pr 60 --quant $quant --channelscaling 1
#	python findoptimal.py --acc 72.3 --pr 70 --quant $quant --channelscaling 1
#	python findoptimal.py --acc 72.3 --pr 80 --quant $quant --channelscaling 1
#	python findoptimal.py --acc 72.3 --pr 90 --quant $quant --channelscaling 1
#	python findoptimal.py --acc 72.3 --pr 95 --quant $quant --channelscaling 1
#	python findoptimal.py --acc 72.3 --pr 97 --quant $quant --channelscaling 1
#	python findoptimal.py --acc 72.3 --pr 98 --quant $quant --channelscaling 1
#	python findoptimal.py --acc 72.3 --pr 99 --quant $quant --channelscaling 1
#	echo ""
#	((quant--))
#done
#echo "channel width 0.75"
#quant=16
#while [ $quant -ge 8 ]
#do
#	python findoptimal.py --acc 72.3 --pr 0 --quant $quant --channelscaling 0.75 
#	python findoptimal.py --acc 72.3 --pr 50 --quant $quant --channelscaling 0.75
#	python findoptimal.py --acc 72.3 --pr 60 --quant $quant --channelscaling 0.75
#	python findoptimal.py --acc 72.3 --pr 70 --quant $quant --channelscaling 0.75
#	python findoptimal.py --acc 72.3 --pr 80 --quant $quant --channelscaling 0.75
#	python findoptimal.py --acc 72.3 --pr 90 --quant $quant --channelscaling 0.75
#	python findoptimal.py --acc 72.3 --pr 95 --quant $quant --channelscaling 0.75
#	python findoptimal.py --acc 72.3 --pr 97 --quant $quant --channelscaling 0.75
#	python findoptimal.py --acc 72.3 --pr 98 --quant $quant --channelscaling 0.75
#	python findoptimal.py --acc 72.3 --pr 99 --quant $quant --channelscaling 0.75
#	echo ""
#	((quant--))
#done
#echo "channel width 0.5"
#quant=16
#while [ $quant -ge 8 ]
#do
#	python findoptimal.py --acc 72.3 --pr 0 --quant $quant --channelscaling 0.5 
#	python findoptimal.py --acc 72.3 --pr 50 --quant $quant --channelscaling 0.5
#	python findoptimal.py --acc 72.3 --pr 60 --quant $quant --channelscaling 0.5
#	python findoptimal.py --acc 72.3 --pr 70 --quant $quant --channelscaling 0.5
#	python findoptimal.py --acc 72.3 --pr 80 --quant $quant --channelscaling 0.5
#	python findoptimal.py --acc 72.3 --pr 90 --quant $quant --channelscaling 0.5
#	python findoptimal.py --acc 72.3 --pr 95 --quant $quant --channelscaling 0.5
#	python findoptimal.py --acc 72.3 --pr 97 --quant $quant --channelscaling 0.5
#	python findoptimal.py --acc 72.3 --pr 98 --quant $quant --channelscaling 0.5
#	python findoptimal.py --acc 72.3 --pr 99 --quant $quant --channelscaling 0.5
#	echo ""
#	((quant--))
#done
#echo "channel width 0.25"
#quant=16
#while [ $quant -ge 8 ]
#do
#	python findoptimal.py --acc 72.3 --pr 0 --quant $quant --channelscaling 0.25 
#	python findoptimal.py --acc 72.3 --pr 50 --quant $quant --channelscaling 0.25
#	python findoptimal.py --acc 72.3 --pr 60 --quant $quant --channelscaling 0.25
#	python findoptimal.py --acc 72.3 --pr 70 --quant $quant --channelscaling 0.25
#	python findoptimal.py --acc 72.3 --pr 80 --quant $quant --channelscaling 0.25
#	python findoptimal.py --acc 72.3 --pr 90 --quant $quant --channelscaling 0.25
#	python findoptimal.py --acc 72.3 --pr 95 --quant $quant --channelscaling 0.25
#	python findoptimal.py --acc 72.3 --pr 97 --quant $quant --channelscaling 0.25
#	python findoptimal.py --acc 72.3 --pr 98 --quant $quant --channelscaling 0.25
#	python findoptimal.py --acc 72.3 --pr 99 --quant $quant --channelscaling 0.25
#	echo ""
#	((quant--))
#done

############################ size based search #############################
#echo "VGG16"
#python findoptimal.py --netsel 0 --pparam 20
#python findoptimal.py --netsel 0 --pparam 10
#python findoptimal.py --netsel 0 --pparam 9
#python findoptimal.py --netsel 0 --pparam 8
#python findoptimal.py --netsel 0 --pparam 7
#python findoptimal.py --netsel 0 --pparam 6
#python findoptimal.py --netsel 0 --pparam 5
#python findoptimal.py --netsel 0 --pparam 4
#python findoptimal.py --netsel 0 --pparam 3
#python findoptimal.py --netsel 0 --pparam 2
#python findoptimal.py --netsel 0 --pparam 1
#
#echo "ResNet18"
#python findoptimal.py --netsel 1 --pparam 20
#python findoptimal.py --netsel 1 --pparam 10
#python findoptimal.py --netsel 1 --pparam 9
#python findoptimal.py --netsel 1 --pparam 8
#python findoptimal.py --netsel 1 --pparam 7
#python findoptimal.py --netsel 1 --pparam 6
#python findoptimal.py --netsel 1 --pparam 5
#python findoptimal.py --netsel 1 --pparam 4
#python findoptimal.py --netsel 1 --pparam 3
#python findoptimal.py --netsel 1 --pparam 2
#python findoptimal.py --netsel 1 --pparam 1
#
#echo "SqueezeNext"
#python findoptimal.py --netsel 2 --pparam 20
#python findoptimal.py --netsel 2 --pparam 10
#python findoptimal.py --netsel 2 --pparam 9
#python findoptimal.py --netsel 2 --pparam 8
#python findoptimal.py --netsel 2 --pparam 7
#python findoptimal.py --netsel 2 --pparam 6
#python findoptimal.py --netsel 2 --pparam 5
#python findoptimal.py --netsel 2 --pparam 4
#python findoptimal.py --netsel 2 --pparam 3
#python findoptimal.py --netsel 2 --pparam 2
#python findoptimal.py --netsel 2 --pparam 1
#
#echo "MobileNetV2"
#python findoptimal.py --netsel 3 --pparam 20
#python findoptimal.py --netsel 3 --pparam 10
#python findoptimal.py --netsel 3 --pparam 9
#python findoptimal.py --netsel 3 --pparam 8
#python findoptimal.py --netsel 3 --pparam 7
#python findoptimal.py --netsel 3 --pparam 6
#python findoptimal.py --netsel 3 --pparam 5
#python findoptimal.py --netsel 3 --pparam 4
#python findoptimal.py --netsel 3 --pparam 3
#python findoptimal.py --netsel 3 --pparam 2
#python findoptimal.py --netsel 3 --pparam 1

############################ acc based search #############################
#echo "VGG16"
python findoptimal.py --netsel 0 --accdrop 1
python findoptimal.py --netsel 0 --accdrop 2
python findoptimal.py --netsel 0 --accdrop 3
python findoptimal.py --netsel 0 --accdrop 4
python findoptimal.py --netsel 0 --accdrop 5
python findoptimal.py --netsel 0 --accdrop 6
python findoptimal.py --netsel 0 --accdrop 7
python findoptimal.py --netsel 0 --accdrop 8
python findoptimal.py --netsel 0 --accdrop 9
python findoptimal.py --netsel 0 --accdrop 10

echo "ResNet18"
python findoptimal.py --netsel 1 --accdrop 1
python findoptimal.py --netsel 1 --accdrop 2
python findoptimal.py --netsel 1 --accdrop 3
python findoptimal.py --netsel 1 --accdrop 4
python findoptimal.py --netsel 1 --accdrop 5
python findoptimal.py --netsel 1 --accdrop 6
python findoptimal.py --netsel 1 --accdrop 7
python findoptimal.py --netsel 1 --accdrop 8
python findoptimal.py --netsel 1 --accdrop 9
python findoptimal.py --netsel 1 --accdrop 10

echo "SqueezeNext"
python findoptimal.py --netsel 2 --accdrop 1
python findoptimal.py --netsel 2 --accdrop 2
python findoptimal.py --netsel 2 --accdrop 3
python findoptimal.py --netsel 2 --accdrop 4
python findoptimal.py --netsel 2 --accdrop 5
python findoptimal.py --netsel 2 --accdrop 6
python findoptimal.py --netsel 2 --accdrop 7
python findoptimal.py --netsel 2 --accdrop 8
python findoptimal.py --netsel 2 --accdrop 9
python findoptimal.py --netsel 2 --accdrop 10

echo "MobileNetV2"
python findoptimal.py --netsel 3 --accdrop 1
python findoptimal.py --netsel 3 --accdrop 2
python findoptimal.py --netsel 3 --accdrop 3
python findoptimal.py --netsel 3 --accdrop 4
python findoptimal.py --netsel 3 --accdrop 5
python findoptimal.py --netsel 3 --accdrop 6
python findoptimal.py --netsel 3 --accdrop 7
python findoptimal.py --netsel 3 --accdrop 8
python findoptimal.py --netsel 3 --accdrop 9
python findoptimal.py --netsel 3 --accdrop 10
